// Generated by scripts/sync-product.mjs. Do not edit.
pub const DISPLAY_NAME: &str = "Luna Mux";
pub const DATABASE_FILE: &str = "luna-mux.db";
pub const CREDENTIAL_SERVICE: &str = "com.luna.mux.credentials";
pub const PRODUCT_KEY: &str = "luna-mux";
pub const CONNECTION_ARCHIVE_FORMAT: &str = "luna-mux-connections";
