// Generated by scripts/sync-terminal-runtime-contract.mjs. Do not edit.
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[allow(dead_code)]
pub const TERMINAL_RUNTIME_CONTRACT_VERSION: u32 = 7;
#[allow(dead_code)]
pub const TERMINAL_RUNTIME_CURSOR_UNIT: &str = "utf8Bytes";
pub const TERMINAL_RUNTIME_MAX_CURSOR: u64 = 9007199254740991;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum TerminalTransport {
    LocalPty,
    Ssh,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum TerminalTargetKind {
    Powershell,
    Wsl,
    MacosShell,
    Ssh,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum TerminalRuntimeStatus {
    Starting,
    Connecting,
    Running,
    Exited,
    Error,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum TerminalRuntimeExitReason {
    Exited,
    Signaled,
    Closed,
    ConnectionLost,
    Failed,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalCapabilities {
    pub terminal: bool,
    pub resize: bool,
    pub flow_control: bool,
    pub interrupt: bool,
    pub output_cursor: bool,
    pub remote_files: bool,
    pub port_forwarding: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalTarget {
    pub id: String,
    pub label: String,
    pub transport: TerminalTransport,
    pub kind: TerminalTargetKind,
    pub capabilities: TerminalCapabilities,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntimeCreateRequest {
    #[serde(default)]
    pub runtime_id: Option<String>,
    #[serde(default)]
    pub context: Option<TerminalRuntimeContext>,
    pub target_id: String,
    pub title: Option<String>,
    pub cwd: Option<String>,
    pub command: Option<String>,
    pub authentication: Option<TerminalRuntimeAuthentication>,
    #[serde(default)]
    pub managed_agent: Option<TerminalManagedAgentContext>,
    #[serde(skip, default)]
    pub launch_environment: BTreeMap<String, String>,
    pub cols: u32,
    pub rows: u32,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntimeContext {
    pub mux_session_id: String,
    pub pane_id: String,
    pub runtime_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalManagedAgentContext {
    pub mux_session_id: String,
    pub pane_id: String,
    pub runtime_id: String,
    pub agent_id: String,
    pub launch_profile_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(
    tag = "type",
    content = "options",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum TerminalRuntimeAuthentication {
    Ssh {
        credential: Option<String>,
        remember_credential: bool,
        jump_credential: Option<String>,
        remember_jump_credential: bool,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntime {
    pub runtime_id: String,
    pub target_id: String,
    pub title: String,
    pub status: TerminalRuntimeStatus,
    pub capabilities: TerminalCapabilities,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<TerminalRuntimeContext>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub managed_agent: Option<TerminalManagedAgentContext>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntimeStatusEvent {
    pub runtime: TerminalRuntime,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntimeOutputEvent {
    pub runtime_id: String,
    pub start_cursor: u64,
    pub end_cursor: u64,
    pub data: String,
}

impl TerminalRuntimeOutputEvent {
    pub fn new(runtime_id: impl Into<String>, start_cursor: u64, data: impl Into<String>) -> Self {
        let data = data.into();
        let start_cursor = start_cursor.min(TERMINAL_RUNTIME_MAX_CURSOR);
        Self {
            runtime_id: runtime_id.into(),
            start_cursor,
            end_cursor: start_cursor
                .saturating_add(data.len() as u64)
                .min(TERMINAL_RUNTIME_MAX_CURSOR),
            data,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntimeOutputReadResult {
    pub runtime_id: String,
    pub requested_cursor: u64,
    pub earliest_cursor: u64,
    pub next_cursor: u64,
    pub truncated: bool,
    pub data: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TerminalRuntimeExitEvent {
    pub runtime_id: String,
    pub reason: TerminalRuntimeExitReason,
    pub cursor: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signal: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", content = "payload", rename_all = "camelCase")]
pub enum TerminalRuntimeEvent {
    Status(TerminalRuntimeStatusEvent),
    Output(TerminalRuntimeOutputEvent),
    Exit(TerminalRuntimeExitEvent),
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn capabilities() -> TerminalCapabilities {
        TerminalCapabilities {
            terminal: true,
            resize: true,
            flow_control: true,
            interrupt: true,
            output_cursor: true,
            remote_files: true,
            port_forwarding: true,
        }
    }

    #[test]
    fn serializes_status_event_with_camel_case_contract() {
        let event = TerminalRuntimeEvent::Status(TerminalRuntimeStatusEvent {
            runtime: TerminalRuntime {
                runtime_id: "runtime-1".into(),
                target_id: "target-1".into(),
                title: "PowerShell".into(),
                status: TerminalRuntimeStatus::Running,
                capabilities: capabilities(),
                context: None,
                managed_agent: None,
                error: None,
            },
        });
        let value = serde_json::to_value(event).expect("serialize status event");
        assert_eq!(value["type"], "status");
        assert_eq!(value["payload"]["runtime"]["runtimeId"], "runtime-1");
        assert_eq!(value["payload"]["runtime"]["targetId"], "target-1");
        assert_eq!(value["payload"]["runtime"]["status"], "running");
    }

    #[test]
    fn ssh_authentication_uses_camel_case_option_fields() {
        let value = json!({
            "type": "ssh",
            "options": {
                "credential": "secret",
                "rememberCredential": true,
                "jumpCredential": "jump-secret",
                "rememberJumpCredential": false
            }
        });
        let authentication: TerminalRuntimeAuthentication =
            serde_json::from_value(value.clone()).expect("deserialize SSH authentication");
        assert_eq!(
            authentication,
            TerminalRuntimeAuthentication::Ssh {
                credential: Some("secret".into()),
                remember_credential: true,
                jump_credential: Some("jump-secret".into()),
                remember_jump_credential: false,
            }
        );
        assert_eq!(
            serde_json::to_value(authentication).expect("serialize SSH authentication"),
            value
        );
    }

    #[test]
    fn output_cursor_counts_utf8_bytes() {
        let output = TerminalRuntimeOutputEvent::new("runtime-1", 7, "A中");
        assert_eq!(TERMINAL_RUNTIME_CURSOR_UNIT, "utf8Bytes");
        assert_eq!(TERMINAL_RUNTIME_MAX_CURSOR, 9_007_199_254_740_991);
        assert_eq!(output.start_cursor, 7);
        assert_eq!(output.end_cursor, 11);
        let capped = TerminalRuntimeOutputEvent::new("runtime-1", u64::MAX, "abc");
        assert_eq!(capped.start_cursor, TERMINAL_RUNTIME_MAX_CURSOR);
        assert_eq!(capped.end_cursor, TERMINAL_RUNTIME_MAX_CURSOR);
    }

    #[test]
    fn serializes_exit_event_with_optional_process_details() {
        let event = TerminalRuntimeEvent::Exit(TerminalRuntimeExitEvent {
            runtime_id: "runtime-1".into(),
            reason: TerminalRuntimeExitReason::Exited,
            cursor: 42,
            exit_code: Some(0),
            signal: None,
            message: None,
        });
        assert_eq!(
            serde_json::to_value(event).expect("serialize exit event"),
            json!({
                "type": "exit",
                "payload": {
                    "runtimeId": "runtime-1",
                    "reason": "exited",
                    "cursor": 42,
                    "exitCode": 0
                }
            })
        );
    }
}
