// Generated by scripts/sync-terminal-runtime-contract.mjs. Do not edit.
export const TERMINAL_RUNTIME_CONTRACT_VERSION = 7 as const
export const TERMINAL_RUNTIME_CURSOR_UNIT = "utf8Bytes" as const
export const TERMINAL_RUNTIME_MAX_CURSOR = 9007199254740991 as const

export type TerminalTransport = "localPty" | "ssh"
export type TerminalTargetKind = "powershell" | "wsl" | "macosShell" | "ssh"
export type TerminalRuntimeStatus = "starting" | "connecting" | "running" | "exited" | "error"
export type TerminalRuntimeExitReason = "exited" | "signaled" | "closed" | "connectionLost" | "failed"
export type TerminalCapability = "terminal" | "resize" | "flowControl" | "interrupt" | "outputCursor" | "remoteFiles" | "portForwarding"

export interface TerminalCapabilities {
  terminal: boolean
  resize: boolean
  flowControl: boolean
  interrupt: boolean
  outputCursor: boolean
  remoteFiles: boolean
  portForwarding: boolean
}

export interface TerminalTarget {
  id: string
  label: string
  transport: TerminalTransport
  kind: TerminalTargetKind
  capabilities: TerminalCapabilities
}

export interface TerminalRuntimeCreateRequest {
  runtimeId?: string
  context?: TerminalRuntimeContext
  targetId: string
  title?: string
  cwd?: string
  command?: string
  authentication?: TerminalRuntimeAuthentication
  managedAgent?: TerminalManagedAgentContext
  cols: number
  rows: number
}

export interface TerminalRuntimeContext {
  muxSessionId: string
  paneId: string
  runtimeId: string
}

export interface TerminalManagedAgentContext {
  muxSessionId: string
  paneId: string
  runtimeId: string
  agentId: string
  launchProfileId: string
}

export type TerminalRuntimeAuthentication = {
  type: 'ssh'
  options: {
    credential?: string
    rememberCredential: boolean
    jumpCredential?: string
    rememberJumpCredential: boolean
  }
}

export interface TerminalRuntime {
  runtimeId: string
  targetId: string
  title: string
  status: TerminalRuntimeStatus
  capabilities: TerminalCapabilities
  context?: TerminalRuntimeContext
  managedAgent?: TerminalManagedAgentContext
  error?: string
}

export interface TerminalRuntimeStatusEvent {
  runtime: TerminalRuntime
}

export interface TerminalRuntimeOutputEvent {
  runtimeId: string
  startCursor: number
  endCursor: number
  data: string
}

export interface TerminalRuntimeOutputReadResult {
  runtimeId: string
  requestedCursor: number
  earliestCursor: number
  nextCursor: number
  truncated: boolean
  data: string
}

export interface TerminalRuntimeExitEvent {
  runtimeId: string
  reason: TerminalRuntimeExitReason
  cursor: number
  exitCode?: number
  signal?: string
  message?: string
}

export type TerminalRuntimeEvent =
  | { type: 'status'; payload: TerminalRuntimeStatusEvent }
  | { type: 'output'; payload: TerminalRuntimeOutputEvent }
  | { type: 'exit'; payload: TerminalRuntimeExitEvent }
