import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const metadataPath = path.join(root, 'product', 'product.json')
const checkOnly = process.argv.includes('--check')
const product = JSON.parse(fs.readFileSync(metadataPath, 'utf8'))

const required = [
  'productKey',
  'version',
  'displayName',
  'description',
  'executableName',
  'packageName',
  'bundleId',
  'databaseName',
  'credentialService',
  'protocolScheme'
]
for (const key of required) {
  if (typeof product[key] !== 'string' || !product[key].trim()) {
    throw new Error(`product/product.json: ${key} must be a non-empty string`)
  }
}

const generated = new Map([
  ['app/frontend/src/product-info.ts', `// Generated by scripts/sync-product.mjs. Do not edit.\nexport const PRODUCT_INFO = ${JSON.stringify(product, null, 2)} as const\n`],
  ['app/native/src/product.rs', `// Generated by scripts/sync-product.mjs. Do not edit.\npub const DISPLAY_NAME: &str = ${JSON.stringify(product.displayName)};\npub const DATABASE_FILE: &str = ${JSON.stringify(product.databaseName)};\npub const CREDENTIAL_SERVICE: &str = ${JSON.stringify(product.credentialService)};\npub const PRODUCT_KEY: &str = ${JSON.stringify(product.productKey)};\npub const CONNECTION_ARCHIVE_FORMAT: &str = ${JSON.stringify(`${product.productKey}-connections`)};\n`]
])

const packagePath = path.join(root, 'package.json')
const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'))
packageJson.name = product.packageName
packageJson.version = product.version
packageJson.description = product.description
generated.set('package.json', `${JSON.stringify(packageJson, null, 2)}\n`)

const tauriPath = path.join(root, 'app', 'native', 'tauri.conf.json')
const tauri = JSON.parse(fs.readFileSync(tauriPath, 'utf8'))
tauri.productName = product.displayName
tauri.version = product.version
tauri.identifier = product.bundleId
tauri.app.windows[0].title = product.displayName
tauri.bundle.shortDescription = product.description
generated.set('app/native/tauri.conf.json', `${JSON.stringify(tauri, null, 2)}\n`)

const cargoPath = path.join(root, 'app', 'native', 'Cargo.toml')
const cargo = fs.readFileSync(cargoPath, 'utf8')
  .replace(/^name = ".*"$/m, `name = ${JSON.stringify(product.packageName)}`)
  .replace(/^version = ".*"$/m, `version = ${JSON.stringify(product.version)}`)
  .replace(/^description = ".*"$/m, `description = ${JSON.stringify(`Tauri desktop shell for ${product.displayName}`)}`)
  .replace(/^(\[lib\][\s\S]*?^name = ").*("$)/m, `$1${product.productKey.replaceAll('-', '_')}_lib$2`)
generated.set('app/native/Cargo.toml', cargo)

const capabilityPath = path.join(root, 'app', 'native', 'capabilities', 'default.json')
const capability = JSON.parse(fs.readFileSync(capabilityPath, 'utf8'))
capability.description = `Main ${product.displayName} window permissions`
generated.set('app/native/capabilities/default.json', `${JSON.stringify(capability, null, 2)}\n`)

const indexPath = path.join(root, 'app', 'frontend', 'index.html')
const indexHtml = fs.readFileSync(indexPath, 'utf8').replace(/<title>.*?<\/title>/, `<title>${product.displayName}</title>`)
generated.set('app/frontend/index.html', indexHtml)

const releaseWorkflowPath = path.join(root, '.github', 'workflows', 'release.yml')
const artifactStem = product.displayName.replaceAll(/\s+/g, '-')
const releaseWorkflow = fs.readFileSync(releaseWorkflowPath, 'utf8')
  .replace(/"release-assets\/[^"]+_macos-\$\{\{ matrix\.arch \}\}\.dmg"/, `"release-assets/${artifactStem}_macos-\${{ matrix.arch }}.dmg"`)
  .replace(/"release-assets\/[^"]+_windows-x64-\$\{\{ matrix\.variant \}\}-setup\.exe"/, `"release-assets/${artifactStem}_windows-x64-\${{ matrix.variant }}-setup.exe"`)
  .replace(/--title "[^"]+ \$GITHUB_REF_NAME"/, `--title "${product.displayName} $GITHUB_REF_NAME"`)
generated.set('.github/workflows/release.yml', releaseWorkflow)

let stale = false
const normalizeNewlines = (value) => value.replace(/\r\n?/g, '\n')
for (const [relative, content] of generated) {
  const target = path.join(root, relative)
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : ''
  if (normalizeNewlines(current) === normalizeNewlines(content)) continue
  stale = true
  if (checkOnly) {
    console.error(`Product metadata output is stale: ${relative}`)
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, normalizeNewlines(content), 'utf8')
    console.log(`Updated ${relative}`)
  }
}

if (checkOnly && stale) process.exit(1)
